In [2]:
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.neural_network import MLPClassifier

In [8]:
train = pd.read_csv('mnist_train.csv')
train

label  1x1  1x2  1x3  1x4  1x5  ...  28x23  28x24  28x25  28x26  28x27  28x28
0          5    0    0    0    0    0  ...      0      0      0      0      0      0
1          0    0    0    0    0    0  ...      0      0      0      0      0      0
2          4    0    0    0    0    0  ...      0      0      0      0      0      0
3          1    0    0    0    0    0  ...      0      0      0      0      0      0
4          9    0    0    0    0    0  ...      0      0      0      0      0      0
...      ...  ...  ...  ...  ...  ...  ...    ...    ...    ...    ...    ...    ...
59995      8    0    0    0    0    0  ...      0      0      0      0      0      0
59996      3    0    0    0    0    0  ...      0      0      0      0      0      0
59997      5    0    0    0    0    0  ...      0      0      0      0      0      0
59998      6    0    0    0    0    0  ...      0      0      0      0      0      0
59999      8    0    0    0    0    0  ...      0      0      0      0      0      0

[60000 rows x 785 columns]

In [9]:
test = pd.read_csv('mnist_test.csv')
test

label  1x1  1x2  1x3  1x4  1x5  ...  28x23  28x24  28x25  28x26  28x27  28x28
0         7    0    0    0    0    0  ...      0      0      0      0      0      0
1         2    0    0    0    0    0  ...      0      0      0      0      0      0
2         1    0    0    0    0    0  ...      0      0      0      0      0      0
3         0    0    0    0    0    0  ...      0      0      0      0      0      0
4         4    0    0    0    0    0  ...      0      0      0      0      0      0
...     ...  ...  ...  ...  ...  ...  ...    ...    ...    ...    ...    ...    ...
9995      2    0    0    0    0    0  ...      0      0      0      0      0      0
9996      3    0    0    0    0    0  ...      0      0      0      0      0      0
9997      4    0    0    0    0    0  ...      0      0      0      0      0      0
9998      5    0    0    0    0    0  ...      0      0      0      0      0      0
9999      6    0    0    0    0    0  ...      0      0      0      0      0      0

[10000 rows x 785 columns]

In [10]:
X_train = train.drop(['label'], axis=1)/255
y_train = train.label
print(X_train.shape)
print(y_train.shape)

(60000, 784)
(60000,)


In [11]:
X_test = test.drop(['label'], axis=1)/255
y_test = test.label
print(X_test.shape)
print(y_test.shape)

(10000, 784)
(10000,)


In [14]:
mlp = MLPClassifier(hidden_layer_sizes = (128,128,64,32,16,), max_iter = 60, solver = 'adam', learning_rate_init=0.01)
mlp.fit(X_train,y_train)
pred = mlp.predict(X_test)
print(metrics.accuracy_score(y_test,pred))
print(metrics.classification_report(y_test,pred))
print(metrics.confusion_matrix(y_test,pred))

0.9759
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.96      0.99      0.97      1032
           3       0.97      0.98      0.98      1010
           4       0.99      0.96      0.98       982
           5       0.98      0.96      0.97       892
           6       0.98      0.98      0.98       958
           7       0.98      0.97      0.98      1028
           8       0.95      0.96      0.95       974
           9       0.97      0.98      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000

[[ 972    1    1    0    0    0    2    0    2    2]
 [   0 1121    3    2    0    1    1    1    6    0]
 [   0    0 1018    2    2    0    1    4    5    0]
 [   0    0    5  991    0    4    0    3    6    1]
 [   2    1    4    0 

In [3]:
4+5

9

In [12]:
import numpy

In [13]:
import tensorflow as tf

In [ ]:
tensorflow