## Name : Tirth Hihoriya
## Roll no : 18bce244
## Prac- 6 : RNN for Language Modeling

In [54]:
from numpy import array
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import SimpleRNN
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences
import numpy as np

## Input corpus

In [55]:
data = """ I often get nostalgic remembering the cherished moments which I shared with Shanky. 
We used to play game after game of chess, for hours at a stretch. 
We shared, all our notes and often helped each other with school assignments and projects. 
He was party to all my pranks which we planned at our secret hideout, the tree-house."""
print ("Data:", data, type(data) )

Data:  I often get nostalgic remembering the cherished moments which I shared with Shanky. 
We used to play game after game of chess, for hours at a stretch. 
We shared, all our notes and often helped each other with school assignments and projects. 
He was party to all my pranks which we planned at our secret hideout, the tree-house. <class 'str'>


In [56]:
data_splitted=data.split('\n') #returns a list of strings
print("Data_Splitted:", data_splitted, type(data_splitted))

Data_Splitted: [' I often get nostalgic remembering the cherished moments which I shared with Shanky. ', 'We used to play game after game of chess, for hours at a stretch. ', 'We shared, all our notes and often helped each other with school assignments and projects. ', 'He was party to all my pranks which we planned at our secret hideout, the tree-house.'] <class 'list'>


## Tokenizer

In [57]:
tokenizer=Tokenizer(filters='!"#$%&()*+,-/:;<=>?@[\\]^_`{|}~\t\n',)
tokenizer

In [58]:
tokenizer.fit_on_texts(data_splitted)
print("Word Indices:", tokenizer.word_index) #tokenizer.word_index is a dictionary

Word Indices: {'we': 1, 'i': 2, 'often': 3, 'the': 4, 'which': 5, 'shared': 6, 'with': 7, 'to': 8, 'game': 9, 'at': 10, 'all': 11, 'our': 12, 'and': 13, 'get': 14, 'nostalgic': 15, 'remembering': 16, 'cherished': 17, 'moments': 18, 'shanky.': 19, 'used': 20, 'play': 21, 'after': 22, 'of': 23, 'chess': 24, 'for': 25, 'hours': 26, 'a': 27, 'stretch.': 28, 'notes': 29, 'helped': 30, 'each': 31, 'other': 32, 'school': 33, 'assignments': 34, 'projects.': 35, 'he': 36, 'was': 37, 'party': 38, 'my': 39, 'pranks': 40, 'planned': 41, 'secret': 42, 'hideout': 43, 'tree': 44, 'house.': 45}


In [59]:
vocab_size = len(tokenizer .word_index) + 1
print ("Vocab Size:", vocab_size)

Vocab Size: 46


In [60]:
sequences=tokenizer.texts_to_sequences(data_splitted)  #list of 4 list
l=len(sequences)
print("Sequences:", sequences,"\n", type(sequences), l)

Sequences: [[2, 3, 14, 15, 16, 4, 17, 18, 5, 2, 6, 7, 19], [1, 20, 8, 21, 9, 22, 9, 23, 24, 25, 26, 10, 27, 28], [1, 6, 11, 12, 29, 13, 3, 30, 31, 32, 7, 33, 34, 13, 35], [36, 37, 38, 8, 11, 39, 40, 5, 1, 41, 10, 12, 42, 43, 4, 44, 45]] 
 <class 'list'> 4


In [61]:
X = list()
y = list()

for i in range(l):
    X.insert(i,sequences[i][:-1])
    y.insert(i,sequences[i])

print("X=", X , type(X), "\ny=", y, type(y))

X= [[2, 3, 14, 15, 16, 4, 17, 18, 5, 2, 6, 7], [1, 20, 8, 21, 9, 22, 9, 23, 24, 25, 26, 10, 27], [1, 6, 11, 12, 29, 13, 3, 30, 31, 32, 7, 33, 34, 13], [36, 37, 38, 8, 11, 39, 40, 5, 1, 41, 10, 12, 42, 43, 4, 44]] <class 'list'> 
y= [[2, 3, 14, 15, 16, 4, 17, 18, 5, 2, 6, 7, 19], [1, 20, 8, 21, 9, 22, 9, 23, 24, 25, 26, 10, 27, 28], [1, 6, 11, 12, 29, 13, 3, 30, 31, 32, 7, 33, 34, 13, 35], [36, 37, 38, 8, 11, 39, 40, 5, 1, 41, 10, 12, 42, 43, 4, 44, 45]] <class 'list'>


In [62]:
maxlen = max([len(sequence) for sequence in X])
maxlen

16

## Pre padding

In [63]:
X = pad_sequences(X, maxlen=maxlen+1, padding='pre')
print("X=", X , type(X),"Shape = ", X.shape)

y = pad_sequences(y, maxlen=maxlen+1, padding='pre')
print("\ny=", y , type(y),"Shape = ", y.shape)

X= [[ 0  0  0  0  0  2  3 14 15 16  4 17 18  5  2  6  7]
 [ 0  0  0  0  1 20  8 21  9 22  9 23 24 25 26 10 27]
 [ 0  0  0  1  6 11 12 29 13  3 30 31 32  7 33 34 13]
 [ 0 36 37 38  8 11 39 40  5  1 41 10 12 42 43  4 44]] <class 'numpy.ndarray'> Shape =  (4, 17)

y= [[ 0  0  0  0  2  3 14 15 16  4 17 18  5  2  6  7 19]
 [ 0  0  0  1 20  8 21  9 22  9 23 24 25 26 10 27 28]
 [ 0  0  1  6 11 12 29 13  3 30 31 32  7 33 34 13 35]
 [36 37 38  8 11 39 40  5  1 41 10 12 42 43  4 44 45]] <class 'numpy.ndarray'> Shape =  (4, 17)


## One hot

In [64]:
y = to_categorical(y, num_classes = vocab_size)
print("\ny=", y , type(y),"Shape = ", y.shape)


y= [[[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 1. 0.]
  [0. 0. 0. ... 0. 0. 1.]]] <class 'numpy.ndarray'> Shape =  (4, 17, 46)


## Model

In [65]:
model = Sequential()
model.add(Embedding(input_dim = vocab_size, output_dim=10))
model.add(SimpleRNN(units = 50, return_sequences = True))
model.add(Dense(units=vocab_size, activation='softmax'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, None, 10)          460       
_________________________________________________________________
simple_rnn_2 (SimpleRNN)     (None, None, 50)          3050      
_________________________________________________________________
dense_2 (Dense)              (None, None, 46)          2346      
Total params: 5,856
Trainable params: 5,856
Non-trainable params: 0
_________________________________________________________________


In [66]:
model.compile(optimizer = 'adam',
              loss= 'categorical_crossentropy',
              metrics = ['accuracy'])

In [70]:
model.fit(X, y, epochs=180)

Epoch 1/180
1/1 [==============================] - 0s 5ms/step - loss: 0.2638 - accuracy: 0.9559
Epoch 2/180
1/1 [==============================] - 0s 4ms/step - loss: 0.2611 - accuracy: 0.9559
Epoch 3/180
1/1 [==============================] - 0s 5ms/step - loss: 0.2585 - accuracy: 0.9559
Epoch 4/180
1/1 [==============================] - 0s 5ms/step - loss: 0.2559 - accuracy: 0.9559
Epoch 5/180
1/1 [==============================] - 0s 4ms/step - loss: 0.2533 - accuracy: 0.9559
Epoch 6/180
1/1 [==============================] - 0s 5ms/step - loss: 0.2509 - accuracy: 0.9559
Epoch 7/180
1/1 [==============================] - 0s 4ms/step - loss: 0.2484 - accuracy: 0.9559
Epoch 8/180
1/1 [==============================] - 0s 5ms/step - loss: 0.2461 - accuracy: 0.9559
Epoch 9/180
1/1 [==============================] - 0s 4ms/step - loss: 0.2437 - accuracy: 0.9559
Epoch 10/180
1/1 [==============================] - 0s 5ms/step - loss: 0.2415 - accuracy: 0.9559
Epoch 11/180
1/1 [===========

1/1 [==============================] - 0s 4ms/step - loss: 0.1183 - accuracy: 0.9559
Epoch 168/180
1/1 [==============================] - 0s 4ms/step - loss: 0.1181 - accuracy: 0.9559
Epoch 169/180
1/1 [==============================] - 0s 4ms/step - loss: 0.1179 - accuracy: 0.9559
Epoch 170/180
1/1 [==============================] - 0s 5ms/step - loss: 0.1176 - accuracy: 0.9559
Epoch 171/180
1/1 [==============================] - 0s 4ms/step - loss: 0.1174 - accuracy: 0.9559
Epoch 172/180
1/1 [==============================] - 0s 5ms/step - loss: 0.1172 - accuracy: 0.9559
Epoch 173/180
1/1 [==============================] - 0s 5ms/step - loss: 0.1170 - accuracy: 0.9559
Epoch 174/180
1/1 [==============================] - 0s 5ms/step - loss: 0.1168 - accuracy: 0.9559
Epoch 175/180
1/1 [==============================] - 0s 5ms/step - loss: 0.1166 - accuracy: 0.9559
Epoch 176/180
1/1 [==============================] - 0s 4ms/step - loss: 0.1164 - accuracy: 0.9559
Epoch 177/180
1/1 [=====

In [86]:
# generate probability of an input sentence. This estimate is P(w1)"P(w2[w1)"P(w3|w1, w2)"P(w4|w1, w2, w3)".....
# This is because model was trained to predict the next word based on the all preceding word

def prob_of_input_sentence(model, tokenizer, input_sentence):
    print("\n\nInput Sentence: ", input_sentence)
    encoded = tokenizer.texts_to_sequences([input_sentence])[0]
#     print("Encoded  :", encoded)
    encoded.insert(0,0)

    encoded=array(encoded)
    encoded=np.reshape( encoded, newshape=(1, -1))
    print("Encoded : ", encoded, encoded.shape, encoded.ndim)
    
    prob = model.predict_proba(encoded, verbose=0)
    print("Prob: ", prob.shape)
    
    probability = 1
    for i in range(prob.shape[1]-1):
        probability = probability*prob[0,i,encoded[0,i+1]]
    print("\nProb of sentence - ", "\"", input_sentence , "\"", "is : ", probability)
    
    
prob_of_input_sentence(model, tokenizer, "game of chess after school")




Input Sentence:  game of chess after school
Encoded :  [[ 0  9 23 24 22 33]] (1, 6) 2
Prob:  (1, 6, 46)

Prob of sentence -  " game of chess after school " is :  2.604424797777865e-18


In [72]:
prob_of_input_sentence(model, tokenizer, " other with school assignments and projects")




Input Sentence:   other with school assignments and projects
Encoded [[ 0 32  7 33 34 13]] (1, 6)
Prob of sentence -  "  other with school assignments and projects " is :  3.018147887654018e-20


In [75]:
prob_of_input_sentence (model, tokenizer, "all our notes")




Input Sentence:  all our notes
Encoded [[ 0 11 12 29]] (1, 4)
Prob of sentence -  " all our notes " is :  3.5313143081888116e-10


In [74]:
prob_of_input_sentence(model, tokenizer, "to fetch a pail of water")




Input Sentence:  to fetch a pail of water
Encoded [[ 0  8 27 23]] (1, 4)
Prob of sentence -  " to fetch a pail of water " is :  8.069660599102207e-12
